server:
  port: 8081

spring:
  application:
    name: itmayiedu-xxl-jobs

logging:
  config: classpath:logback.xml


xxl:
  job:
    admin:
      ### xxl-job admin address list：调度中心部署跟地址：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"。
      addresses: http://127.0.0.1:7003/xxl-job-admin
    executor:
      ### xxl-job executor address：执行器"AppName"和地址信息配置：AppName执行器心跳注册分组依据；地址信息用于"调度中心请求并触发任务"和"执行器注册"。
      ### 执行器默认端口为9999，执行器IP默认为空表示自动获取IP，多网卡时可手动设置指定IP，手动设置IP时将会绑定Host。单机部署多个执行器时，注意要配置不同执行器端口；
      appName: xxl-job-executor-itmayiedu
      ###注册器服务的ip地址
      ip: 127.0.0.1
      ####执行器的端口号
      port: 9999
      ### xxl-job log path：执行器运行日志文件存储的磁盘位置，需要对该路径拥有读写权限
      logPath: /data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days：执行器Log文件定期清理功能，指定日志保存天数，日志文件过期自动删除。限制至少保持3天，否则功能不生效；
      logRetentionDays: 30
    ### xxl-job, access token：执行器通讯TOKEN，非空时启用
    accessToken:



###服务注册到eureka地址
eureka:
  client:
    service-url:
      # 写上2个集群服务地址，中间用逗号隔开就行
      defaultZone: http://127.0.0.1:8100/eureka
    ###当前会员服务注册到eureka
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true


    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    instance:
      ###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
      lease-renewal-interval-in-seconds: 1
      ####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
      lease-expiration-duration-in-seconds: 2
