###注册 中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 7001
###网关名称
spring:
  application:
    name: service-zuul
### 配置网关反向代理
zuul:
  routes:
    ##api-a 定义转发的规则
    api-a:
      ### 当客户端发送请求127.0.0.1:80//api-member 开头的 都会转发到会员服务
      path: /api-member/**
      ## 会员服务别名, zuul 网关默认整合ribbon 自动实现负载均衡轮询效果
      serviceId: itmayiedu-api-member-service-impl
    api-b:
      ### 当客户端发送请求127.0.0.1:80//api-order 开头的 都会转发到订单服务
      path: /api-order/**
      serviceId: itmayiedu-api-order-service-impl
  host:
    socket-timeout-millis: 12000
    connect-timeout-millis: 12000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 240000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000








