###服务启动端口号
server:
  port: 8080
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: itmayiedu-api-member-service-impl
  datasource:
    url: jdbc:mysql://localhost:3306/itmayiedu-member?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

###服务注册到eureka地址
eureka:
  client:
    service-url:
      # 写上2个集群服务地址，中间用逗号隔开就行
      defaultZone: http://127.0.0.1:8100/eureka
    ###当前会员服务注册到eureka
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true


    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    instance:
      ###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
      lease-renewal-interval-in-seconds: 1
      ####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
      lease-expiration-duration-in-seconds: 2



# swagger 扫描包范围
swagger:
  base-package: com.itmayiedu.api.service.impl

##
##日志配置

mybatis-plus:
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-column-underline: true
    field-strategy: 1
    id-type: 0
    logic-delete-value: 1
    logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.itmayiedu.api.entity




tx-lcn:
  client:
    ##LCN 客户端连接tx-manager 全局事务注册中心
    manager-address: 127.0.0.1:8070
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
